title: Freelancer Protocol
url: "https://docs.freelancerprotocol.com"
remote_theme: pmarsceill/just-the-docs
title: "Documentation"
# logo: "https://www.freelancerprotocol.com/logo192.png"
aux_links:
  "Go to Freelancer Protocol":
    - "//www.freelancerprotocol.com/"
