title: Freelancer Protocol
url: "https://docs.freelancerprotocol.com"
remote_theme: pmarsceill/just-the-docs
title: "FAQ"
# logo: "https://www.freelancerprotocol.com/logo192.png"
aux_links:
  "Back to Freelancer Protocol":
    - "//www.freelancerprotocol.com/"
