title: Freelancer Protocol
remote_theme: pmarsceill/just-the-docs
title: "Documentation"
# logo: "https://www.freelancerprotocol.com/logo192.png"
aux_links:
  "Back to Dashboard":
    - "//www.freelancerprotocol.com/"
